[package]
name = "d2"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
color-eyre = "0.6"
atty = "0.2"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
